import Head from 'next/head'
import Image from 'next/image'
import type {GetServerSideProps} from 'next'
import { TemplateCanvas } from '@croct/template-ui/next'
import { renderMarkdown } from '?/**/*/markdown.{tsx,js}'
import { fetchContent } from '@croct/plug-next/server'
import type { SlotContent } from '@croct/plug-next'
import { Inter } from 'next/font/google'
import styles from '?/**/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export type HomeProps = {
  content: SlotContent<'%slotId%@%slotVersion%'>
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async context => ({
  props: await fetchContent('%slotId%@%slotVersion%', {route: context})
});

export default function Home({content}: HomeProps) {
  return (
    <TemplateCanvas
      title="Next.js 13 starter"
      ctaLabel="Edit this page"
      ctaLink="%workspaceUrl%/slots/edit/%slotId%/%slotVersion%"
      ctaTarget="_blank"
      src="#"
      fullScreen
      portal
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            {renderMarkdown(content.hint, {code: styles.code})}
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=croct&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          {content.links.map(link => (
            <a
              key={link.url}
              href={link.url}
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                {link.title} <span>-&gt;</span>
              </h2>
              <p>{link.description}</p>
            </a>
          ))}
        </div>
      </main>
    </TemplateCanvas>
  )
}
